apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: my-app-cluster      
 region: us-east-1          
 version: "1.29"            

managedNodeGroups:
 - name: general-nodes
   instanceType: t3.small     
   desiredCapacity: 3         
   minSize: 2
   maxSize: 5
   iam:
     withAddonPolicies:
       ebs: true